// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // DIRECT_URL bypasses pgbouncer for prisma migrate (DDL requires a direct connection).
    // Set to the Supabase direct URL (port 5432); DATABASE_URL stays on port 6543 for runtime.
    directUrl: process.env["DIRECT_URL"],
  },
});
