// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // datasource.url is used by the schema engine (migrate/introspect) only — not by PrismaClient.
  // Point to DIRECT_URL (port 5432) so DDL bypasses pgbouncer (port 6543).
  // PrismaClient runtime uses @prisma/adapter-pg with DATABASE_URL independently (src/lib/prisma.ts).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
